/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medecin;

import java.sql.*;
import java.text.DateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.Date;
import java.util.ArrayList;
import java.util.Iterator;
/**
 *
 * @author Lenovo
 */
public class ORDONNANCE extends javax.swing.JFrame {
connexionBD conn=new connexionBD ();
    Statement stmt ;
    ResultSet Rs ;
    DefaultTableModel model=new DefaultTableModel();
    /**
     * Creates new form ORDONNANCE
     */
    public ORDONNANCE() {
        initComponents();
        this.setTitle("ORDONNANCE");//nom de la fenetre 
    //Nous demandons maintenant à notre objet de se positionner au centre
    this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        
         model.addColumn("CODE DE MEDICAMENT");
        model.addColumn("NOM DE MEDICAMENT");
        model.addColumn("FAMILLE DE MEDICAMENT");
        model.addColumn("FORME DE MEDICAMENT");
        model.addColumn("DOSAGE DE MEDICAMENT");
        try {
            stmt=conn.getconnexionBD ().createStatement();
            ResultSet Rs =stmt.executeQuery ("Select * from medicament");
            while (Rs.next()){
                model.addRow(new Object[]{Rs.getString("id"),Rs.getString("nom"),Rs.getString("famille"),
                    Rs.getString("forme"),Rs.getString("dosage")});
            }
        }
        catch (Exception e){System.err.println(e);}
        table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdo = new javax.swing.JTextField();
        txtfor = new javax.swing.JTextField();
        txtfam = new javax.swing.JTextField();
        txtno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        principale2 = new javax.swing.JPanel();
        nomcabinet2 = new javax.swing.JLabel();
        ordo2 = new javax.swing.JLabel();
        pat2 = new javax.swing.JLabel();
        nompren2 = new javax.swing.JLabel();
        nomprenom2 = new javax.swing.JTextPane();
        dr2 = new javax.swing.JLabel();
        nommed2 = new javax.swing.JTextPane();
        num2 = new javax.swing.JLabel();
        codepatient2 = new javax.swing.JTextPane();
        photo2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        medic2 = new javax.swing.JTextArea();
        date2 = new javax.swing.JLabel();
        dateorg2 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        imprimer = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 573));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("GESTION DES MEDICAMENTS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("NOM DE MEDICAMENT :");

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("FAMILLE DE MEDICAMENT :");

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("FORME DE MEDICAMENT :");

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("DOSAGE DE MEDICAMENT :");

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("La Liste des Medicaments:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        table.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODE DE MEDICAMENT", "NOM DE MEDICAMENT", "FAMILLE DE MEDICAMENT", "FORME DE MEDICAMENT", "DOSAGE DE MEDICAMENT"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Viner Hand ITC", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medecin/trouver-recherche-zoom-icone-4884-16.png"))); // NOI18N
        jButton1.setText("Recherche Par FAMILLE :");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_rech.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medecin/fleche-cycle-actualisez-icone-7641-16.png"))); // NOI18N
        jButton2.setText("Actualiser");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ajouter.setBackground(new java.awt.Color(0, 51, 102));
        ajouter.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medecin/ajouter-crayon-icone-4828-16.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouterMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ajouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtdo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtfam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(100, 100, 100)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_rech)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );

        principale2.setBackground(new java.awt.Color(255, 255, 255));
        principale2.setAutoscrolls(true);
        principale2.setEnabled(false);
        principale2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principale2MouseClicked(evt);
            }
        });

        nomcabinet2.setBackground(new java.awt.Color(153, 153, 153));
        nomcabinet2.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        nomcabinet2.setText("Cabinet Medical ");
        nomcabinet2.setToolTipText("");

        ordo2.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        ordo2.setText("Ordonnance ");

        pat2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        pat2.setText("patient (e);");

        nompren2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        nompren2.setText("Nom et prenom:");

        nomprenom2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nomprenom2.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        nomprenom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomprenom2MouseClicked(evt);
            }
        });
        nomprenom2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomprenom2KeyPressed(evt);
            }
        });

        dr2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        dr2.setText("Dr.");

        nommed2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nommed2.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N

        num2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        num2.setText("Numero :");

        codepatient2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        codepatient2.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N

        medic2.setColumns(20);
        medic2.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        medic2.setRows(5);
        medic2.setText("\n\n\n\n\n\n\n\n\n\n");
        medic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medic2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(medic2);

        date2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        date2.setText("Le:");

        dateorg2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dateorg2.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N
        dateorg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateorg2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout principale2Layout = new javax.swing.GroupLayout(principale2);
        principale2.setLayout(principale2Layout);
        principale2Layout.setHorizontalGroup(
            principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principale2Layout.createSequentialGroup()
                .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principale2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(principale2Layout.createSequentialGroup()
                                .addComponent(dr2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nommed2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principale2Layout.createSequentialGroup()
                                    .addComponent(num2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(codepatient2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principale2Layout.createSequentialGroup()
                                    .addComponent(nompren2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nomprenom2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pat2)
                            .addGroup(principale2Layout.createSequentialGroup()
                                .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(principale2Layout.createSequentialGroup()
                                        .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nomcabinet2)
                                            .addGroup(principale2Layout.createSequentialGroup()
                                                .addComponent(photo2)
                                                .addGap(477, 477, 477)))
                                        .addGap(130, 130, 130))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principale2Layout.createSequentialGroup()
                                        .addComponent(date2)
                                        .addGap(18, 18, 18)))
                                .addComponent(dateorg2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(principale2Layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(ordo2))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        principale2Layout.setVerticalGroup(
            principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principale2Layout.createSequentialGroup()
                .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principale2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(principale2Layout.createSequentialGroup()
                                .addComponent(photo2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(dr2))
                            .addComponent(nommed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(principale2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomcabinet2)
                        .addGap(59, 59, 59)
                        .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date2)
                            .addComponent(dateorg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(ordo2)
                .addGap(42, 42, 42)
                .addComponent(pat2)
                .addGap(18, 18, 18)
                .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num2)
                    .addComponent(codepatient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(principale2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nompren2)
                    .addComponent(nomprenom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 993, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principale2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1383, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel1);

        imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medecin/imprimante-icone-6110-16.png"))); // NOI18N
        imprimer.setText("Imprimer");
        imprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimerMouseClicked(evt);
            }
        });
        imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerActionPerformed(evt);
            }
        });
        jMenuBar1.add(imprimer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try {
            int i=table.getSelectedRow();deplace(i);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            model.setRowCount(0);
            {
                Rs=stmt.executeQuery ("Select * from medicament where famille = '"+txt_rech.getText()+"'");
            }while (Rs.next()){
                Object [] medicament ={Rs.getInt(1),Rs.getString(2),Rs.getString(3),
                    Rs.getString(4),Rs.getString(5)};
                model.addRow(medicament);}
            if (model.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"il y a aucun medicament");
            }
            else {int i=0;
                deplace (i);
            }
        }
        catch (Exception e){System.err.println(e);
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            model.setRowCount(0);
            stmt=conn.getconnexionBD().createStatement();
            ResultSet Rs =stmt.executeQuery ("Select * from medicament");
            while (Rs.next()){
                model.addRow(new Object[]{Rs.getString("id"),Rs.getString("nom"),Rs.getString("famille"),
                    Rs.getString("forme"),Rs.getString("dosage")});
        }
        }
        catch (Exception e){System.err.println(e);}
        table.setModel(model);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked

        String one=txtno.getText();
        String two=txtfam.getText();
        String three=txtfor.getText();
        String four=txtdo.getText();
        String tt=one+"\n"+two+"\n"+three+"\n"+four;
        String p=medic2.getText();
        if(p==null){
            medic2.setText(tt);
        }else{

            medic2.setText(p+"\n\n"+tt);}

        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterMouseClicked

    private void nomprenom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomprenom2MouseClicked
        String codepatientt =codepatient2.getText();

        try {

            stmt =conn.getconnexionBD().createStatement();
            ResultSet result =stmt.executeQuery("SELECT * FROM patient;" );//execute la requete
            //JOptionPane.showMessageDialog(null,"requete succes");afiche que la requete a marcher

            int x=0;
            String NOM="";
            String PRENOM="";

            while (( result.next())&&( x==0)){

                String codep = result.getString( "idPatient" )+"";

                if (codep.equals(codepatientt)){
                    x=1;
                    NOM = result.getString( "nom" );
                    PRENOM = result.getString("prenom" );}
            }
            if(x==1)
            {
                nomprenom2.setText(NOM+"    "+PRENOM);

            }else{
                codepatient2.setText("");
            }

        }catch(SQLException ex){//le type de l exception ici c est SQLException qui est predefinie dans la class exception
            System.out.println(ex);//il t affiche la raison pk le try ne marche pas
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nomprenom2MouseClicked

    private void nomprenom2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomprenom2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomprenom2KeyPressed

    private void medic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medic2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_medic2MouseClicked

    private void dateorg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateorg2MouseClicked
        Date aujourdhui = new Date();
        DateFormat shortDateFormat = DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT);
        String t=shortDateFormat+"";
        dateorg2.setText(shortDateFormat.format(aujourdhui));        // TODO add your handling code here:
    }//GEN-LAST:event_dateorg2MouseClicked

    private void principale2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principale2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_principale2MouseClicked

    private void imprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimerMouseClicked
        MPanelPrinter printP = new MPanelPrinter(principale2);
        printP.print();  // TODO add your handling code here:
    }//GEN-LAST:event_imprimerMouseClicked

    private void imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimerActionPerformed

    private void ajouterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMousePressed



ajouter.setBackground(new java.awt.Color(204,0,51));         // TODO add your handling code here:
    }//GEN-LAST:event_ajouterMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
jButton1.setBackground(new java.awt.Color(204,0,51)); 

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed

jButton2.setBackground(new java.awt.Color(204,0,51)); 

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed
private void deplace (int i){
        try {
            txtno.setText(model.getValueAt(i,1).toString());
            txtfam.setText(model.getValueAt(i,2).toString());
            txtfor.setText(model.getValueAt(i,3).toString());
            txtdo.setText(model.getValueAt(i,4).toString());
        }
        catch (Exception e){System.err.println(e);
        JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORDONNANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORDONNANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORDONNANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORDONNANCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORDONNANCE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JTextPane codepatient2;
    private javax.swing.JLabel date2;
    private javax.swing.JTextPane dateorg2;
    private javax.swing.JLabel dr2;
    private javax.swing.JMenu imprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea medic2;
    private javax.swing.JLabel nomcabinet2;
    private javax.swing.JTextPane nommed2;
    private javax.swing.JLabel nompren2;
    private javax.swing.JTextPane nomprenom2;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel ordo2;
    private javax.swing.JLabel pat2;
    private javax.swing.JLabel photo2;
    private javax.swing.JPanel principale2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_rech;
    private javax.swing.JTextField txtdo;
    private javax.swing.JTextField txtfam;
    private javax.swing.JTextField txtfor;
    private javax.swing.JTextField txtno;
    // End of variables declaration//GEN-END:variables

 private void JOptionPaneshowMessageDialog(ORDONNANCE aThis, String svp_entrer_quelque_chose) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}